### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Artep666** [MarikIshtar007/MarikIshtar007#4]
Hey, I really liked the pun u threw in there about binary code!^-^
as to the suggestion ,it will be cool if u put a visitors counter +it will match with the vibe  have going on with the black and green 
here's how:
![Visitor Count](https://profile-counter.glitch.me/{YOUR USER}/count.svg)

**Comment by MarikIshtar007** [comment]
Yeah. I could use that. However I already have a visitor count. Its just above the binary code pun

**Comment by Artep666** [comment]
omg you are  right,guess I am indeed in need of glasses,damnit
